[workspace]
authors = ["Ivan Aphanasyev <nekaktotak2@gmail.com>"]
channels = ["conda-forge", "robostack-kilted"]
name = "rotation_estimation"
platforms = ["osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]
"ide:mac" = "./scripts/activate-ide-profile.sh mac"
"ide:pi5" = "./scripts/activate-ide-profile.sh pi5"

[activation.env]
RMW_IMPLEMENTATION = "rmw_zenoh_cpp"

[feature.mac-viz.activation.env]
RMW_IMPLEMENTATION = "rmw_zenoh_cpp"

[feature.mac-viz.activation]
scripts = ["scripts/activate-ros-env.sh"]

[feature.pi-runtime.activation.env]
RMW_IMPLEMENTATION = "rmw_zenoh_cpp"

[feature.pi-runtime.activation]
scripts = ["scripts/activate-ros-env.sh"]

[dependencies]
numpy = ">=2.5.1,<3"
pytest = ">=9.1.1,<10"

[feature.mac-viz]
platforms = ["osx-arm64"]
channels = ["robostack-kilted", "conda-forge"]

[feature.pi-runtime]
platforms = ["linux-aarch64"]
channels = ["robostack-kilted", "conda-forge"]

[feature.mac-viz.tasks]
rviz = "rviz2"
zenohd = "./scripts/run-zenohd.sh"
rerun = "rerun"
heartbeat_listener = "ros2 topic echo /m1_heartbeat"
heartbeat_publisher = "ros2 topic pub /m1_heartbeat std_msgs/msg/Int32 '{data: 1}' --rate 1"

[feature.pi-runtime.tasks]
zenohd = "./scripts/run-zenohd.sh"
heartbeat_listener = "ros2 topic echo /m1_heartbeat"
sensehat_udp_reader = "/usr/bin/python3 src/sensehat_udp_sidecar/sensehat_udp_reader.py"
sensehat_imu = "PYTHONPATH=src python -m rotation_estimation_nodes.sensehat_imu_node"
sensehat_imu_mock = "PYTHONPATH=src python -m rotation_estimation_nodes.sensehat_imu_node --ros-args -p mock:=true"

[feature.mac-viz.dependencies]
ros-kilted-ros-core = "*"
ros-kilted-rmw-zenoh-cpp = "*"
ros-kilted-rviz2 = "*"
rerun-sdk = "*"

[feature.pi-runtime.dependencies]
ros-kilted-ros-core = "*"
ros-kilted-rmw-zenoh-cpp = "*"
ros-kilted-rclpy = ">=9.1.5,<10"
ros-kilted-sensor-msgs = "*"

[feature.dev-tools.dependencies]
ruff = ">=0.15.20,<0.16"
ty = ">=0.0.56,<0.0.57"


[environments]
mac-viz = { features = ["mac-viz", "dev-tools"], no-default-feature = true }
pi-runtime = { features = [
    "pi-runtime",
    "dev-tools",
], no-default-feature = true }
